### ISSUE TITLE
Vercel DB integration issue

### ISSUE THREAD

**Issue by chandasampath** [ixartz/SaaS-Boilerplate#32]
Am seeing the following error after adding Vercel Postgresql DB integration:

```
[19:32:09.139] Cloning completed: 662.128ms
[19:32:18.678] Restored build cache
[19:32:18.797] Running "vercel build"
[19:32:19.961] Vercel CLI 37.1.2
[19:32:21.918] Installing dependencies...
[19:32:27.655] 
[19:32:27.656] > saas-boilerplate@1.4.3 prepare
[19:32:27.656] > husky
[19:32:27.657] 
[19:32:27.734] 
[19:32:27.735] removed 1 package in 6s
[19:32:27.735] 
[19:32:27.735] 437 packages are looking for funding
[19:32:27.736]   run `npm fund` for details
[19:32:27.748] Detected Next.js version: 14.2.5
[19:32:27.767] Running "npm run build"
[19:32:28.018] 
[19:32:28.018] > saas-boilerplate@1.4.3 build
[19:32:28.019] > next build
[19:32:28.019] 
[19:32:29.162]   ▲ Next.js 14.2.5
[19:32:29.162]   - Environments: .env.production, .env
[19:32:29.163]   - Experiments (use with caution):
[19:32:29.163]     · instrumentationHook
[19:32:29.163] 
[19:32:29.232]    Creating an optimized production build ...
[19:32:29.862] [@sentry/nextjs - Node.js] Warning: No auth token provided. Will not create release. Please set the `authToken` option. You can find information on how to generate a Sentry auth token here: https://docs.sentry.io/api/auth/
[19:32:29.862] [@sentry/nextjs - Node.js] Warning: No auth token provided. Will not upload source maps. Please set the `authToken` option. You can find information on how to generate a Sentry auth token here: https://docs.sentry.io/api/auth/
[19:32:52.963] [@sentry/nextjs - Edge] Warning: No auth token provided. Will not create release. Please set the `authToken` option. You can find information on how to generate a Sentry auth token here: https://docs.sentry.io/api/auth/
[19:32:52.963] [@sentry/nextjs - Edge] Warning: No auth token provided. Will not upload source maps. Please set the `authToken` option. You can find information on how to generate a Sentry auth token here: https://docs.sentry.io/api/auth/
[19:32:58.260] [@sentry/nextjs - Client] Warning: No auth token provided. Will not create release. Please set the `authToken` option. You can find information on how to generate a Sentry auth token here: https://docs.sentry.io/api/auth/
[19:32:58.261] [@sentry/nextjs - Client] Warning: No auth token provided. Will not upload source maps. Please set the `authToken` option. You can find information on how to generate a Sentry auth token here: https://docs.sentry.io/api/auth/
[19:33:15.682]  ✓ Compiled successfully
[19:33:15.683]    Linting and checking validity of types ...
[19:33:37.283]    Collecting page data ...
[19:33:39.789] error: expected one dependency record for TOAST table, found 4
[19:33:39.790]     at Ke.parseErrorMessage (file:///vercel/path0/node_modules/@electric-sql/pglite/dist/chunk-OVRU7FYL.js:1:12967)
[19:33:39.795]     at Ke.handlePacket (file:///vercel/path0/node_modules/@electric-sql/pglite/dist/chunk-OVRU7FYL.js:1:9640)
[19:33:39.795]     at Ke.parse (file:///vercel/path0/node_modules/@electric-sql/pglite/dist/chunk-OVRU7FYL.js:1:8285)
[19:33:39.796]     at file:///vercel/path0/node_modules/@electric-sql/pglite/dist/chunk-OVRU7FYL.js:1:23863
[19:33:39.797]     at Array.forEach (<anonymous>)
[19:33:39.797]     at file:///vercel/path0/node_modules/@electric-sql/pglite/dist/chunk-OVRU7FYL.js:1:23841
[19:33:39.797]     at file:///vercel/path0/node_modules/@electric-sql/pglite/dist/chunk-OVRU7FYL.js:1:16185
[19:33:39.797]     at ge.<anonymous> (file:///vercel/path0/node_modules/@electric-sql/pglite/dist/chunk-OVRU7FYL.js:1:14634)
[19:33:39.797]     at Generator.next (<anonymous>)
[19:33:39.797]     at l (file:///vercel/path0/node_modules/@electric-sql/pglite/dist/chunk-OVRU7FYL.js:1:14020) {
[19:33:39.798]   length: 121,
[19:33:39.798]   severity: 'ERROR',
[19:33:39.798]   code: 'XX000',
[19:33:39.799]   detail: undefined,
[19:33:39.799]   hint: undefined,
[19:33:39.799]   position: undefined,
[19:33:39.799]   internalPosition: undefined,
[19:33:39.799]   internalQuery: undefined,
[19:33:39.800]   where: undefined,
[19:33:39.800]   schema: undefined,
[19:33:39.801]   table: undefined,
[19:33:39.801]   column: undefined,
[19:33:39.801]   dataType: undefined,
[19:33:39.801]   constraint: undefined,
[19:33:39.801]   file: 'cluster.c',
[19:33:39.802]   line: '1253',
[19:33:39.802]   routine: 'swap_relation_files'
[19:33:39.802] }
[19:33:39.804] 
[19:33:39.804] > Build error occurred
[19:33:39.808] Error: Failed to collect page data for /[locale]/api/submit-waitlist-email
[19:33:39.809]     at /vercel/path0/node_modules/next/dist/build/utils.js:1268:15 {
[19:33:39.809]   type: 'Error'
[19:33:39.809] }
[19:33:39.949] Error: Command "npm run build" exited with 1
[19:33:40.522] 
```

Any idea how to solve this issue?

**Comment by chandasampath** [comment]
Fixed by going back to a working commit, and re-applying required DB integration related changes.

**Comment by ixartz** [comment]
@chandasampath Awesome! Thank you for letting us know.
